### ISSUE TITLE
database of file mimetypes

### ISSUE THREAD

**Issue by RaitaroH** [YodaEmbedding/frece#4]
I also have a script that opens files for me. Thanks to your script I can make it a lot faster and smarter so thank you for that. I am working rn to update all my rofi scripts with your frece.

I was toying with rofi and it's markup fuctionality. Here is an example for only dirs:

```
file=$(find -type d | \
      sed "s/^/\<span\ lang='folder'\ foreground='#3daee9'\ face='Font Awesome'>\&#xf07b;<\/span>\ /" | \
      rofi -dmenu -multi-select -theme green -i -markup-rows -l 20 -p "What songs?" | \
      awk -F'</span> ' '{print $2}' )
```
So result is as such:

![image](https://user-images.githubusercontent.com/19552720/60345532-ee769f00-99c1-11e9-9ae1-1f6b1e662a6d.png)

The idea was for frence to perhaps also keep the mimetype of the entry. This way I can simply pass the database through sed first. If say you were to keep the thing in a separate file that would be awesome. Obv I would need a command like `pr -tmJ icons.txt search_results.txt | rofi`, where the icons.txt was the database changed with sed as below. The problem this idea of mine faced was that getting the mimetype was too bloody slow to actually be practical.

```
sed -i -e "s/inode\/directory/\<span\ lang='folder'\ foreground='#3daee9'\ face='Font Awesome'>\&xf07b;<\/span>/
    s/inode\/symlink/\<span\ lang='link'\ foreground='#76a1e2'\ face='Font Awesome'>\&xf0c1;<\/span>/
    s/inode.*/\<span\ lang='file-text'\ foreground='#ffcfa0'\ face='Font Awesome'>\&xf15c;<\/span>/
    s/audio.*/\<span\ lang='music'\ foreground='#f193f9'\ face='Font Awesome'>\&xf001;<\/span>/
    s/text\/x-shellscript/\<span\ lang='terminal'\ foreground='#fbc9ff'\ face='Font Awesome'>\&xf120;<\/span>/
    s/text.*/\<span\ lang='file-text'\ foreground='#ffcfa0'\ face='Font Awesome'>\&xf15c;<\/span>/
    s/image.*/\<span\ lang='picture-o'\ foreground='#b373f4'\ face='Font Awesome'>\&xf03e;<\/span>/
    s/video.*/\<span\ lang='file-video-o'\ foreground='#a1fccb'\ face='Font Awesome'>\&xf1c8;<\/span>/
    s/application\/pdf/\<span\ lang='file-pdf-o'\ foreground='#ef7a84'\ face='Font Awesome'>\&xf1c1;<\/span>/
    s/application\/x-executable/\<span\ lang='file-code-o'\ foreground='#a3f1ff'\ face='Font Awesome'>\&xf1c9;<\/span>/
    s/application.*/\<span\ lang='cogs'\ foreground='#fffdb5'\ face='Font Awesome'>\&xf085;<\/span>/
    s/application\/zip/\<span\ lang='archive'\ foreground='#b9ef83'\ face='Font Awesome'>\&xf187;<\/span>/"
```

**Comment by SicariusNoctis** [comment]
You can always just keep the mimetypes with the entries themselves.

Does this work?

```
pr -tmJ icons.txt search_results.txt > entries.txt

frece init files.db entries.txt
frece print files.db | rofi
```

**Comment by YodaEmbedding** [comment]
Is the following a correct reformulation of your problem?

`files.txt` contains what is displayed by `rofi` and `mimetypes.txt` contains "metadata" that is not visible to rofi.

```bash
echo "apple
banana.mp3
cherry" > files.txt

echo "directory
file
directory" > mimetypes.txt

frece init files.db files.txt

# Usage
item=$(frece print files.db | rofi -dmenu)
frece increment files.db "$item"
mimetype=$(frece lookup mimetypes.txt "$item")  # not an actual command
echo "$item has mimetype $mimetype"
```

This only works for rofi, but one hacky solution is to keep the filenames and mimetypes together, but make the mimetypes invisible:

```bash
echo "<!-- directory --> apple
<!-- file --> banana.mp3
<!-- directory --> cherry" > files.txt
```

The `<!-- ... -->` comment will be invisible to the `rofi` GUI.

A more general solution would probably involve some sort of GUID or lookup-table... which might be outside the scope of `frece`'s initial goal, but might be useful to integrate for performance reasons.

**Comment by RaitaroH** [comment]
Well the `item=$(frece print files.db | rofi -dmenu)` is not correct because for my usage the mimetype needs to be present in rofi as well. I will use your repository for frece as an example

files.txt - output of `ls` in this case
```
Cargo.lock
Cargo.toml
ci
examples
LICENSE
README.md
src
```
mimetype.txt - output of `file -b --mime-type`
```
text/plain
text/plain
inode/directory
inode/directory
text/plain
text/plain
inode/directory
```
But this mimetypes are not 100% invisibile to rofi because the mimetype.txt is useless by itself. I process it with sed (truncated sed):
```
sed -i -e "s/inode\/directory/\<span\ lang='folder'\ foreground='#3daee9'\ face='Font Awesome'>\&xf07b;<\/span>/ ...." mimetype.txt > mimetype_sed.txt
```
The result mimetype_sed.txt is like so. This can have music files, pdf files etc:
```
<span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>
<span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>
<span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>
<span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>
<span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>
<span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>
<span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>
```
Now that I have the mimetype processed in the markup I can finally combine that with the files:
```
pr -tmJ mimetype_sed.txt files.txt  | rofi -i -markup-rows -l 20 -p "What to open?"
```
In essence rofi needs to see `<span>...</span> Cargo.lock` for the markup to work as in the picture below.
![image](https://user-images.githubusercontent.com/19552720/60379824-6389b900-9a42-11e9-9d74-928a57de2b6e.png)

Now, using `file -b --mime-type` is really slow. How frece would keep the mime type is not much of a concern as long as the mimetype and the file that belongs to are perfectly matched. So the command `frece increment files.db "$item"` needs to be executed another time for the mimetypes too `frece increment mimetypes.db "$item"`. So I think it might just be better having the mimetypes in the database itself so the 2nd increment wouldn't be needed. `frece lookup files.db` could simply output the mimetypes alone as in mimetype.txt example above.

**Comment by YodaEmbedding** [comment]
Isn't this what you're trying to achieve? MCVE:

```bash
#!/bin/bash

git clone https://github.com/SicariusNoctis/frece
cd frece || exit

# Setup
ls >files.txt
file -b --mime-type -f files.txt >mimetypes.txt
sed -e "
    s/\(inode\/directory\)/<\!-- & --> <span lang='folder' foreground='#3daee9' face='Font Awesome'>\&#xf07b;<\/span>/
    s/\(text.*\)/<\!-- & --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>\&#xf15c;<\/span>/
" mimetypes.txt >mimetypes_sed.txt
pr -tmJ mimetypes_sed.txt files.txt >entries.txt
frece init files.db entries.txt

# Usage
item=$(frece print files.db | rofi -dmenu -markup-rows)
if [[ -n $item ]]; then
    frece increment files.db "$item"
    filepath=$(sed -e 's/^<!-- [^ ]* --> <span[^>]*>[^<]*<\/span[^>]*>\t//g' <<<"$item")
    mimetype=$(sed -e 's/^<!-- \([^ ]*\) --> .*$/\1/g' <<<"$item")

    echo ""
    echo "filepath: $filepath"
    echo "mimetype: $mimetype"
    echo ""
    frece print files.db --verbose
fi
```

Expected output (if choosing `LICENSE` in rofi):

```bash
filepath: LICENSE
mimetype: text/plain

0.627115       1  2019-06-29T12:05:52+00:00  <!-- text/plain --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>        LICENSE
0.000000       0  1970-01-01T00:00:00+00:00  <!-- text/plain --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>        Cargo.lock
0.000000       0  1970-01-01T00:00:00+00:00  <!-- text/plain --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>        Cargo.toml
0.000000       0  1970-01-01T00:00:00+00:00  <!-- inode/directory --> <span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>      ci
0.000000       0  1970-01-01T00:00:00+00:00  <!-- inode/directory --> <span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>      examples
0.000000       0  1970-01-01T00:00:00+00:00  <!-- text/plain --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>        files.txt
0.000000       0  1970-01-01T00:00:00+00:00  <!-- text/plain --> <span lang='file-text' foreground='#ffcfa0' face='Font Awesome'>&#xf15c;</span>        README.md
0.000000       0  1970-01-01T00:00:00+00:00  <!-- inode/directory --> <span lang='folder' foreground='#3daee9' face='Font Awesome'>&#xf07b;</span>      src
```

What does this fail to do? What are the downsides to this? I'm sorry, but I still can't understand the issue/goal.

**Comment by RaitaroH** [comment]
In essence, I was suggesting not relying on `file -b --mime-type` due to being very impractical for a large pool of data, if possible. 

I think I could simply not update the database often for the code you provided.

Thank you for the script :innocent:

**Comment by YodaEmbedding** [comment]
Hmm... the only reasonable way I see that working is to apply `file -b --mime-type` on *only* new/modified files. (Perhaps get a list of new files using `find -mmin [MINUTES]`? Or refresh on [only filesystem events](https://unix.stackexchange.com/questions/24952/script-to-monitor-folder-for-new-files/24955#24955).)

Once you have a list of new files, get their mimetypes, and add them to `entries.txt`. You may wish to ensure they're sorted in some order (e.g. alphabetical). This is all outside `frece`'s goal of managing databases, so I'm hesitant to add it. But there may already be a way to do it with existing UNIX tools (or python script)... Once `entries.txt` contains all the files you want, just run `frece update files.db entries.txt --purge-old`.

There is also the issue of files *changing* their mimetype, though that's probably too unlikely a corner case to worry about.
