### ISSUE TITLE
print --verbose is undocumented in help

### ISSUE THREAD

**Issue by nwwdles** [YodaEmbedding/frece#5]
Hello! Thank you for making a great piece of software. 
Sometimes I want to use frece to only print items by recency and I always forget how to do it and since it's not documented in `--help`, I have to open the github page and read the examples to rediscover `--verbose`. It would be nice for help to mention the flag.

Actually, I think it would be nice to have a `print-recent` option to do just that, instead of having to call awk and sort (well, I probably should put it into a separate issue)
```sh
frece print "$FRECENCY_DB" --verbose \
        | sort -r -k 2 \
        | awk '{print $4}'
```

Edit: after checking the commits and updating to 1.0.3, I see that sort methods are already implemented, thank you. I'll leave this open because I think that flag documentation can be improved.

**Comment by nwwdles** [comment]
Seems like I didn't try `frece print --help` which has everything I requested. So I'll close this. :)

**Comment by YodaEmbedding** [comment]
Yeah, I also usually forget about `command subcommand --help` when using other CLI utilities. I do wish there were a standardized way to look at the help, but they all do something different! (`-h`, `--help`, `-help`, `command help`, `command subcommand --help`, `command help subcommand`, `man`, ...)
